### ISSUE TITLE
API Docs: representing vars in API reference Request samples

### ISSUE THREAD

**Issue by tzach** [scylladb/scylladb-cloud-doc-issues#14] opened 2024-02-04 07:10 UTC
I would like to report an issue in page like 
https://cloud.docs.scylladb.com/stable/api.html#tag/Cluster/operation/deleteCluster

### Problem

API include an accountId var

```
https://api.cloud.scylladb.com/account/{accountId}/cluster/{clusterId}/delete
```

The var looks off in the CURL example, since '{}' is converted to '%7'

![image](https://github.com/scylladb/scylladb-cloud-doc-issues/assets/170200/0a7a913f-3134-4e0f-a2e6-3f0d9b9a5638)

Here is how it looks in other reference 

![image](https://github.com/scylladb/scylladb-cloud-doc-issues/assets/170200/53959894-2ab2-44bc-9096-deebcd36c879)

source https://www.cockroachlabs.com/docs/api/cloud/v1#get-/api/scim/v2/Groups/-id-

###  Suggest a fix

Use `{clusterId}` in the CURL example as well

**Comment by annastuchlik** [comment] 2024-02-14 16:20
This is a duplicate of https://github.com/scylladb/siren-frontend/issues/4099.
Fixed with https://github.com/scylladb/scylla-cloud-doc/pull/197.
You can check it here: https://cloud.docs.scylladb.com/stable/api.html#tag/Account-Cluster-Network/operation/getVPCPeeringList (and other examples).
Closing.

**Closed as completed by annastuchlik** 2024-02-14 16:20 UTC
Labels: documentation
