### ISSUE TITLE
docs: Issue in page Create a Personal Token for Authentication

### ISSUE THREAD

**Issue by Kikivsantos** [scylladb/scylladb-cloud-doc-issues#11] opened 2023-12-08 12:18 UTC
I would like to report an issue in page https://cloud.docs.scylladb.com/master/api-docs/create-api-token

### Problem
I'm trying to use the command with my personal token and it's not working. Do I need to install or configure something in my machine first?

command:
curl --request GET --url https://api.cloud.scylladb.com/deployment/cloud-providers --header 'Authorization: Bearer <MY_ERSONA_TOKEN>'

Error:
curl: (60) SSL certificate problem: self-signed certificate in certificate chain
More details here: https://curl.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.

PS: A co-worker of my could run this in hes machine. So it's probably something that I dont have install or cofigured in my machine, but cant find what it is.

Thanks

**Comment by Kikivsantos** [comment] 2023-12-08 12:20
PS: With --insecure it runs fine from my machine.

But I need this to work without the --insecure, so I can run terraform to manage my infrastructure

**Comment by annastuchlik** [comment] 2023-12-08 15:23
Thanks for reporting.

@mixellent @noellymedina @hopugop I'm not sure this is a documentation issue. Could you help out?

**Comment by mrVanboy** [comment] 2023-12-08 20:44
Hello @Kikivsantos

thank you for the report. We were not able to reproduce the issue. I tried to isolate as many things and possible and run everything in the alpine container with docker:

```console

$ docker run --rm -ti alpine

$ apk add curl

$ export API_TOKEN=<TOKEN_VALUE>

# remove the --head flag to see the response
$ curl \
	--header "Authorization: Bearer ${API_TOKEN}" \
	--head \
	 https://api.cloud.scylladb.com/deployment/cloud-providers 

HTTP/2 200
date: Fri, 08 Dec 2023 19:29:41 GMT
content-type: application/json; charset=utf-8
content-length: 137
...
```

It would be helpful to run `curl` with `-v` or `-vv` flags to see more details. Our API should be signed with `ISRG Root X2` and cross-signed with `ISRG Root X1` certificate ([details](https://letsencrypt.org/certificates/)). Those certificate authorities are common in many package managers, if they are relying on [Mozilla's CA Certificate program](https://wiki.mozilla.org/CA/Included_Certificates):
- Ubuntu: https://packages.ubuntu.com/jammy/all/ca-certificates/filelist
- Fedora: https://packages.fedoraproject.org/pkgs/ca-certificates/
- Alpine: https://pkgs.alpinelinux.org/contents?repo=main&arch=x86_64&page=2&name=ca%2dcertificates&branch=edge

So far the only recommendation I could made is to check the root certificates on the machine where `curl` was failing to run. Alternatively same link could be opened in web browser to check if certificates are all-right.

---

I also see that you reported in a terraform repository that `curl` worked as expected:
https://github.com/scylladb/terraform-provider-scylladbcloud/issues/99#issuecomment-1847193983

**Comment by annastuchlik** [comment] 2023-12-08 22:43
@Kikivsantos I hope the answer provided above helps. I'm closing this issue as it's not related to the documentation.
Should you have more questions, please contact ScyllDB Cloud support: [cloud.scylladb.com/support](https://cloud.scylladb.com/support)

**Closed as completed by annastuchlik** 2023-12-08 22:43 UTC
